[pytest]
addopts = -ra --cov=backend --cov-report=term --cov-report=html:coverage --cov-report=lcov:coverage/lcov.info
norecursedirs = old_version
filterwarnings =
    ignore:Support for class-based `config` is deprecated.*
    ignore:on_event is deprecated, use lifespan event handlers instead.*:DeprecationWarning
