[pytest]
addopts = -ra
norecursedirs = old_version
filterwarnings =
    ignore:Support for class-based `config` is deprecated.*
    ignore:on_event is deprecated, use lifespan event handlers instead.*:DeprecationWarning
